package arnold.tasks.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import arnold.tasks.Deadline;
import arnold.tasks.Event;
import arnold.tasks.Task;
import arnold.tasks.Todo;

// Tests generated by OpenCode Kimi K2.5 Free

/**
 * Comprehensive tests for TaskString utility class.
 * Tests the stream-based listWithIndex method and other formatting utilities.
 */
public class TaskStringTest {

    private Task todoTask;
    private Task deadlineTask;
    private Task eventTask;

    @BeforeEach
    public void setUp() {
        todoTask = new Todo("Read book");
        deadlineTask = new Deadline("Submit report", LocalDateTime.of(2024, 12, 25, 0, 0));
        eventTask =
            new Event("Team meeting", LocalDateTime.of(2024, 12, 20, 0, 0), LocalDateTime.of(2024, 12, 21, 0, 0));
    }

    @Test
    public void withIndex_singleDigitIndex_success() {
        String result = TaskString.withIndex(todoTask, 1);
        assertEquals("1.[T][ ] Read book", result);
    }

    @Test
    public void withIndex_doubleDigitIndex_success() {
        String result = TaskString.withIndex(todoTask, 10);
        assertEquals("10.[T][ ] Read book", result);
    }

    @Test
    public void withIndex_tripleDigitIndex_success() {
        String result = TaskString.withIndex(todoTask, 100);
        assertEquals("100.[T][ ] Read book", result);
    }

    @Test
    public void withIndex_zeroIndex_success() {
        String result = TaskString.withIndex(todoTask, 0);
        assertEquals("0.[T][ ] Read book", result);
    }

    @Test
    public void withIndex_markedTask_success() {
        todoTask.mark();
        String result = TaskString.withIndex(todoTask, 1);
        assertEquals("1.[T][X] Read book", result);
    }

    @Test
    public void withIndex_differentTaskTypes_success() {
        assertEquals("1.[T][ ] Read book", TaskString.withIndex(todoTask, 1));
        assertEquals("2.[D][ ] Submit report (by: 25/12/2024 0000)", TaskString.withIndex(deadlineTask, 2));
        assertEquals("3.[E][ ] Team meeting (from: 20/12/2024 0000 to: 21/12/2024 0000)",
            TaskString.withIndex(eventTask, 3));
    }

    @Test
    public void withIndex_emptyDescription_success() {
        Task emptyTask = new Todo("");
        String result = TaskString.withIndex(emptyTask, 1);
        assertEquals("1.[T][ ] ", result);
    }

    @Test
    public void withIndex_negativeIndex_success() {
        String result = TaskString.withIndex(todoTask, -1);
        assertEquals("-1.[T][ ] Read book", result);
    }

    @Test
    public void withoutIndex_basicTask_success() {
        String result = TaskString.withoutIndex(todoTask);
        assertEquals("  [T][ ] Read book", result);
    }

    @Test
    public void withoutIndex_markedTask_success() {
        todoTask.mark();
        String result = TaskString.withoutIndex(todoTask);
        assertEquals("  [T][X] Read book", result);
    }

    @Test
    public void withoutIndex_differentTaskTypes_success() {
        assertEquals("  [T][ ] Read book", TaskString.withoutIndex(todoTask));
        assertEquals("  [D][ ] Submit report (by: 25/12/2024 0000)", TaskString.withoutIndex(deadlineTask));
        assertEquals("  [E][ ] Team meeting (from: 20/12/2024 0000 to: 21/12/2024 0000)",
            TaskString.withoutIndex(eventTask));
    }

    @Test
    public void withoutIndex_emptyDescription_success() {
        Task emptyTask = new Todo("");
        String result = TaskString.withoutIndex(emptyTask);
        assertEquals("  [T][ ] ", result);
    }

    @Test
    public void listWithIndex_emptyList_returnsEmptyString() {
        List<Task> tasks = Collections.emptyList();
        String result = TaskString.listWithIndex(tasks);
        assertEquals("", result);
    }

    @Test
    public void listWithIndex_singleTask_success() {
        List<Task> tasks = List.of(todoTask);
        String result = TaskString.listWithIndex(tasks);
        assertEquals("1.[T][ ] Read book", result);
    }

    @Test
    public void listWithIndex_multipleTasks_correctNumbering() {
        List<Task> tasks = List.of(todoTask, deadlineTask, eventTask);
        String result = TaskString.listWithIndex(tasks);
        String expected = "1.[T][ ] Read book\n"
            + "2.[D][ ] Submit report (by: 25/12/2024 0000)\n"
            + "3.[E][ ] Team meeting (from: 20/12/2024 0000 to: 21/12/2024 0000)";
        assertEquals(expected, result);
    }

    @Test
    public void listWithIndex_largeList_correctNumbering() {
        List<Task> tasks = new ArrayList<>();
        for (int i = 1; i <= 100; i++) {
            tasks.add(new Todo("Task " + i));
        }
        String result = TaskString.listWithIndex(tasks);

        // Verify first line
        assertTrue(result.startsWith("1.[T][ ] Task 1"));
        // Verify last line
        assertTrue(result.endsWith("100.[T][ ] Task 100"));
        // Verify we have 99 newlines (100 tasks = 99 separators)
        assertEquals(99, result.chars().filter(ch -> ch == '\n').count());
    }

    @Test
    public void listWithIndex_mixedMarkedAndUnmarked_success() {
        Task task1 = new Todo("Task 1");
        Task task2 = new Todo("Task 2");
        task2.mark();
        Task task3 = new Todo("Task 3");

        List<Task> tasks = List.of(task1, task2, task3);
        String result = TaskString.listWithIndex(tasks);
        String expected = "1.[T][ ] Task 1\n"
            + "2.[T][X] Task 2\n"
            + "3.[T][ ] Task 3";
        assertEquals(expected, result);
    }

    @Test
    public void listWithIndex_tasksWithSpecialCharacters_success() {
        Task task1 = new Todo("Task with spaces");
        Task task2 = new Todo("Task-with-dashes");
        Task task3 = new Todo("Task/with/slashes");
        Task task4 = new Todo("Task\nwith\nnewlines");

        List<Task> tasks = List.of(task1, task2, task3, task4);
        String result = TaskString.listWithIndex(tasks);

        assertTrue(result.contains("1.[T][ ] Task with spaces"));
        assertTrue(result.contains("2.[T][ ] Task-with-dashes"));
        assertTrue(result.contains("3.[T][ ] Task/with/slashes"));
        assertTrue(result.contains("4.[T][ ] Task\nwith\nnewlines"));
    }

    @Test
    public void listWithIndex_singleTaskInArrayList_success() {
        List<Task> tasks = new ArrayList<>();
        tasks.add(todoTask);
        String result = TaskString.listWithIndex(tasks);
        assertEquals("1.[T][ ] Read book", result);
    }

    @Test
    public void listWithIndex_taskWithLongDescription_success() {
        String longDesc = "This is a very long description that contains many words and "
            + "should still be formatted correctly with the index prefix";
        Task longTask = new Todo(longDesc);
        List<Task> tasks = List.of(longTask);
        String result = TaskString.listWithIndex(tasks);
        assertEquals("1.[T][ ] " + longDesc, result);
    }

    @Test
    public void listWithIndex_allMarkedTasks_success() {
        Task task1 = new Todo("Task 1");
        Task task2 = new Todo("Task 2");
        task1.mark();
        task2.mark();

        List<Task> tasks = List.of(task1, task2);
        String result = TaskString.listWithIndex(tasks);
        String expected = "1.[T][X] Task 1\n2.[T][X] Task 2";
        assertEquals(expected, result);
    }

    @Test
    public void listWithIndex_unmarkedAfterMarked_success() {
        Task task1 = new Todo("Task 1");
        Task task2 = new Todo("Task 2");
        task1.mark();
        // task2 remains unmarked

        List<Task> tasks = List.of(task1, task2);
        String result = TaskString.listWithIndex(tasks);
        String expected = "1.[T][X] Task 1\n2.[T][ ] Task 2";
        assertEquals(expected, result);
    }

    // Integration tests
    @Test
    public void withIndexAndListWithIndex_consistency() {
        // Ensure that withIndex produces the same result as listWithIndex for individual items
        List<Task> tasks = List.of(todoTask, deadlineTask, eventTask);
        String listResult = TaskString.listWithIndex(tasks);

        StringBuilder manualResult = new StringBuilder();
        for (int i = 0; i < tasks.size(); i++) {
            if (i > 0) {
                manualResult.append("\n");
            }
            manualResult.append(TaskString.withIndex(tasks.get(i), i + 1));
        }

        assertEquals(manualResult.toString(), listResult);
    }

    @Test
    public void listWithIndex_immutableList_success() {
        // Test with immutable list (List.of)
        List<Task> tasks = List.of(todoTask, deadlineTask);
        String result = TaskString.listWithIndex(tasks);
        assertTrue(result.contains("1.[T][ ] Read book"));
        assertTrue(result.contains("2.[D][ ] Submit report (by: 25/12/2024 0000)"));
    }

    @Test
    public void listWithIndex_noModificationsToOriginalList() {
        List<Task> originalTasks = new ArrayList<>();
        originalTasks.add(todoTask);
        originalTasks.add(deadlineTask);
        int originalSize = originalTasks.size();

        TaskString.listWithIndex(originalTasks);

        // Ensure the list wasn't modified
        assertEquals(originalSize, originalTasks.size());
        assertEquals(todoTask, originalTasks.get(0));
        assertEquals(deadlineTask, originalTasks.get(1));
    }
}
